import { Router } from 'express';
import { sql } from '../config/db.js';
import bcrypt from 'bcryptjs';
import { exigirAutenticacao, exigirTipo } from '../middlewares/auth.js';
import { mapFornecedor } from '../controllers/authController.js';

const router=Router(); const admin=[exigirAutenticacao,exigirTipo('admin')]; const fornecedor=[exigirAutenticacao,exigirTipo('fornecedor')];
const select=`f.id,f.nome_negocio,f.responsavel,f.email,f.telefone,f.categoria_id,f.descricao,f.cidade,f.endereco,f.foto_url,f.faixa_preco,f.estado_conta,f.criado_em,f.atualizado_em,c.nome AS categoria_nome`;
function out(f){return {...mapFornecedor(f),categoriaNome:f.categoria_nome||null};}

router.get('/', async(req,res)=>{try{const rows=await sql`SELECT ${sql.unsafe(select)} FROM fornecedores f LEFT JOIN categorias c ON c.id=f.categoria_id WHERE f.estado_conta='ativo' ORDER BY f.id DESC`;res.json({ok:true,fornecedores:rows.map(out)});}catch(e){console.error(e);res.status(500).json({ok:false,erro:'Erro ao consultar fornecedores.'});}});
router.get('/me', ...fornecedor, async(req,res)=>{try{const [f]=await sql`SELECT ${sql.unsafe(select)} FROM fornecedores f LEFT JOIN categorias c ON c.id=f.categoria_id WHERE f.id=${Number(req.usuario.id)} LIMIT 1`;if(!f)return res.status(404).json({ok:false,erro:'Fornecedor não encontrado.'});res.json({ok:true,fornecedor:out(f)});}catch(e){console.error(e);res.status(500).json({ok:false,erro:'Erro ao consultar fornecedor.'});}});
router.get('/:id', async(req,res)=>{const id=Number(req.params.id);try{const [f]=await sql`SELECT ${sql.unsafe(select)} FROM fornecedores f LEFT JOIN categorias c ON c.id=f.categoria_id WHERE f.id=${id} LIMIT 1`;if(!f)return res.status(404).json({ok:false,erro:'Fornecedor não encontrado.'});res.json({ok:true,fornecedor:out(f)});}catch(e){console.error(e);res.status(500).json({ok:false,erro:'Erro ao consultar fornecedor.'});}});
router.patch('/me', ...fornecedor, async(req,res)=>{const b=req.body||{};try{const [f]=await sql`SELECT * FROM fornecedores WHERE id=${Number(req.usuario.id)} LIMIT 1`;if(!f)return res.status(404).json({ok:false,erro:'Fornecedor não encontrado.'});const categoriaId=b.categoriaId===''||b.categoriaId==null?f.categoria_id:Number(b.categoriaId);await sql`UPDATE fornecedores SET nome_negocio=${String(b.nomeNegocio??f.nome_negocio).trim()},responsavel=${String(b.responsavel??f.responsavel).trim()},email=${String(b.email??f.email).trim().toLowerCase()},telefone=${b.telefone??f.telefone},categoria_id=${categoriaId},descricao=${b.descricao??f.descricao},cidade=${b.cidade??f.cidade},endereco=${b.endereco??f.endereco},foto_url=${b.fotoUrl??f.foto_url},faixa_preco=${b.faixaPreco??f.faixa_preco} WHERE id=${f.id}`;const [u]=await sql`SELECT ${sql.unsafe(select)} FROM fornecedores f LEFT JOIN categorias c ON c.id=f.categoria_id WHERE f.id=${f.id}`;res.json({ok:true,fornecedor:out(u)});}catch(e){console.error(e);res.status(e?.code==='23505'?409:500).json({ok:false,erro:e?.code==='23505'?'Email já utilizado.':'Não foi possível atualizar o fornecedor.'});}});
router.get('/pendentes/lista', ...admin, async(req,res)=>{try{const rows=await sql`SELECT ${sql.unsafe(select)} FROM fornecedores f LEFT JOIN categorias c ON c.id=f.categoria_id WHERE f.estado_conta='pendente' ORDER BY f.id DESC`;res.json({ok:true,fornecedores:rows.map(out)});}catch(e){console.error(e);res.status(500).json({ok:false,erro:'Erro ao consultar fornecedores pendentes.'});}});
router.get('/admin/lista', ...admin, async(req,res)=>{try{const rows=await sql`SELECT ${sql.unsafe(select)} FROM fornecedores f LEFT JOIN categorias c ON c.id=f.categoria_id ORDER BY f.id DESC`;res.json({ok:true,fornecedores:rows.map(out)});}catch(e){console.error(e);res.status(500).json({ok:false,erro:'Erro ao listar fornecedores.'});}});
router.patch('/:id/aprovar', ...admin, async(req,res)=>{const id=Number(req.params.id);try{const r=await sql`UPDATE fornecedores SET estado_conta='ativo' WHERE id=${id} RETURNING *`;if(!r.length)return res.status(404).json({ok:false,erro:'Fornecedor não encontrado.'});res.json({ok:true,fornecedor:mapFornecedor(r[0]),mensagem:'Fornecedor aprovado.'});}catch(e){console.error(e);res.status(500).json({ok:false,erro:'Não foi possível aprovar o fornecedor.'});}});
router.patch('/:id/reprovar', ...admin, async(req,res)=>{const id=Number(req.params.id);try{const r=await sql`UPDATE fornecedores SET estado_conta='inativo' WHERE id=${id} RETURNING *`;if(!r.length)return res.status(404).json({ok:false,erro:'Fornecedor não encontrado.'});res.json({ok:true,fornecedor:mapFornecedor(r[0]),mensagem:'Fornecedor reprovado.'});}catch(e){console.error(e);res.status(500).json({ok:false,erro:'Não foi possível reprovar o fornecedor.'});}});
router.post('/me/password', ...fornecedor, async(req,res)=>{const atual=String(req.body?.passwordAtual||''),nova=String(req.body?.novaPassword||'');if(nova.length<8)return res.status(400).json({ok:false,erro:'A nova palavra-passe deve ter pelo menos 8 caracteres.'});try{const [f]=await sql`SELECT password_hash FROM fornecedores WHERE id=${Number(req.usuario.id)} LIMIT 1`;if(!f||!(await bcrypt.compare(atual,f.password_hash)))return res.status(401).json({ok:false,erro:'Palavra-passe atual incorreta.'});const h=await bcrypt.hash(nova,10);await sql`UPDATE fornecedores SET password_hash=${h} WHERE id=${Number(req.usuario.id)}`;res.json({ok:true,mensagem:'Palavra-passe alterada.'});}catch(e){console.error(e);res.status(500).json({ok:false,erro:'Não foi possível alterar a palavra-passe.'});}});
export default router;
