import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import './config/db.js';
import authRoutes from './routes/auth.js';
import casalRoutes from './routes/casal.js';
import fornecedorRoutes from './routes/fornecedor.js';
import categoriaRoutes from './routes/categoria.js';
import servicoRoutes from './routes/servico.js';
import solicitacaoRoutes from './routes/solicitacao.js';
import convidadoRoutes from './routes/convidado.js';
import notificacaoRoutes from './routes/notificacao.js';
import adminRoutes from './routes/admin.js';

const app=express();
const PORT=Number(process.env.PORT||8080);
const allowed=(process.env.CORS_ORIGIN||'*').split(',').map(s=>s.trim());
app.use(cors({origin:(origin,cb)=>{if(!origin||allowed.includes('*')||allowed.includes(origin))return cb(null,true);return cb(new Error('Origem não permitida pelo CORS.'));}}));
app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:true}));
app.get('/',(req,res)=>res.json({ok:true,message:'Backend do Enlace rodando com sucesso!',versao:'2.0.0'}));
app.get('/api/health',async(req,res)=>{try{await import('./config/db.js').then(({sql})=>sql`SELECT 1`);res.json({ok:true,banco:'conectado'});}catch(e){console.error(e);res.status(503).json({ok:false,banco:'indisponível'});}});
app.use('/api/auth',authRoutes);
app.use('/api/casal',casalRoutes);
app.use('/api/fornecedor',fornecedorRoutes);
app.use('/api/categorias',categoriaRoutes);
app.use('/api/servicos',servicoRoutes);
app.use('/api/solicitacoes',solicitacaoRoutes);
app.use('/api/convidados',convidadoRoutes);
app.use('/api/notificacoes',notificacaoRoutes);
app.use('/api/admin',adminRoutes);
app.use((req,res)=>res.status(404).json({ok:false,erro:'Rota não encontrada.'}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({ok:false,erro:'Erro interno do servidor.'});});
app.listen(PORT,'0.0.0.0',()=>console.log(`Servidor rodando na porta ${PORT}`));
